### ISSUE TITLE
Create binned scatter function

### ISSUE THREAD

**Issue by yu-jia-wang** [gslab-econ/gslab_r#14]
Per comment [here](https://github.com/gslab-econ/ad-price-drivers/issues/503#issuecomment-916384994), goal is to adapt the binned scatter function(s) we use in ad-price-driver for cross-project/repo usage. Relevant code and documentation can be found [here](https://github.com/gslab-econ/ad-price-drivers/tree/ab7ae2f4def6a12261bf384dc473e0dd781a493f/analysis/source/lib/plot) (note not all files in the linked directory is for creating/testing `binscatter.R`).

@jmshapir fyi.

**Comment by jmshapir** [comment]
Steps here:
* bring in code from `ad-price-drivers`
* revise it to work as a standalone R package
* add some unit testing

**Comment by jmshapir** [comment]
@ew487 let me know when you're in the repository and I can assign you, thanks!

**Comment by ew487** [comment]
@jmshapir I am here now!

**Comment by jmshapir** [comment]
@ew487 assigning you now! Let me know if anything is unclear here and thanks.

**Comment by ew487** [comment]
@jmshapir Will do! Thanks!

**Comment by ew487** [comment]
Hi @jmshapir, would it be possible to get write access to this repository to push my changes?

**Comment by jmshapir** [comment]
@ew487 done, thanks, please use it wisely!

**Comment by ew487** [comment]
@jmshapir Thanks!

**Comment by jmshapir** [comment]
Per call:
* We'll make this a standalone package.
* Probably fine to include lower-level "helper" functions in the main package file
* @torenfronsdal @jmshapir can review when code is ready

**Comment by ew487** [comment]
[Link](https://github.com/gslab-econ/gslab_r/tree/development-binscatter) to issue branch

**Comment by ew487** [comment]
Hi @jmshapir, I wanted to check something with you because while testing the intercept option I am getting a warning message from R. I think it's because of this code:
![image](https://user-images.githubusercontent.com/108754119/184138461-88992986-f71e-4cf9-aaf7-4898ee56271d.jpeg)

When intercept is true, `y_mean` has zero in the first element and ends up one element longer than `y_se`. So later when the confidence intervals are calculated the correspondence between the two vectors is shifted by one position. Is this intentional?

**Comment by jmshapir** [comment]
@ew487 thanks for flagging this! We haven't been using depicted SEs/CIs too much so I'm not that familiar with how the code handles those.

Take the case where we have 10 decile-spaced bins 1, 2, ..., 10 and we include an intercept, so we estimate the model

`y ~ intercept + bin2 + bin3 + ... + bin10`

Let's call this initial set of coefficients `[bin1, bin2, ..., bin10]` where implicitly `bin1 = 0`.

If we're shifting by a constant to match some overall mean then let that constant be `C` so that the shifted set of coefficients is  `[b1, b2, ..., b10] = [bin1+C, bin2+C, ..., bin10+C]`.

By default, I think we want the confidence interval centered around `b1` to have radius zero, and the confidence interval centered around `bK` for `K>1` to have radius given by `SE_K x crit` where `SE_K` is the standard error on `binK` in the original equation, and `crit` is the appropriate critical value (e.g. 1.96 for 95% CI, etc.). That way we can visually test hypotheses of the form `H0:bK=b1` for any `K`.

Does that make sense?

(If this turns out to be tricky to implement in some way, we can also consider excluding SE/CI functionality from v1.0 of the package, since I don't think we need it at the moment.)

**Comment by jmshapir** [comment]
Per call: hoping to open a pull request in the next couple of days.

**Comment by ew487** [comment]
**Summary**

Issue branch [here](https://github.com/gslab-econ/gslab_r/tree/development-binscatter)
