### ISSUE TITLE
Create and improve the basic classes

### ISSUE THREAD

**Issue by yuchuan2016** [gslab-econ/gslab_r#2]
The goal of this task is to make a first pass on creating and improving the basic gslab_r classes (Model, ModelData, ModelEstimationOutput), which parallel the classes in MATLAB library [gslab_model](https://econ-gentzkow-svn.stanford.edu/repos/main/trunk/lib/matlab/gslab_model/).

**Comment by yuchuan2016** [comment]
Update: We have decided to use RC as our default system of OOP in #3. I'm now working on improving the basic classes.

**Comment by yuchuan2016** [comment]
@gentzkow , I have a question about the optimization tool we want to use in galsb_r. If our goal is to make this package available to public, I suppose we do not want to use Knitro as our optimization tool? There are [many optimization packages in R](https://cran.r-project.org/web/views/Optimization.html). Do we want to pick one as our default (like [`optim`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optim.html)), and override if necessary when creating sub-classes?

**Comment by gentzkow** [comment]
Yes. I think it would be ideal if we could abstract the optimization step
so that it uses optim by default but it's easy for a user to swap in Knitro
or anything else they want to use. (I'm imagining that we provide built in
support for optim and Knitro and then to use something else the user would
need to just override the Optimize method we have defined.)

-- 

Matthew Gentzkow
Professor of Economics
Stanford University

**Comment by yuchuan2016** [comment]
Thread continues at #4.
